# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("grade", models.IntegerField()),
                (
                    "cycle",
                    models.IntegerField(choices=[(1, "1º Ciclo"), (2, "2º Ciclo")]),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("graduado", "Graduado"),
                            ("retido", "Retido"),
                            ("transferido", "Transferido"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.competency",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "competency")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="competencies",
            field=models.ManyToManyField(
                through="academic.StudentCompetency", to="curriculum.competency"
            ),
        ),
    ]
