# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
        ("curriculum", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Alunos"},
        ),
        migrations.AlterModelOptions(
            name="alunocompetencia",
            options={
                "verbose_name": "Competência do Student",
                "verbose_name_plural": "Competências dos Alunos",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="cycle",
            field=models.IntegerField(
                choices=[(1, "1º Ciclo"), (2, "2º Ciclo")], verbose_name="Ciclo"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.IntegerField(verbose_name="Grade"),
        ),
        migrations.AlterField(
            model_name="student",
            name="competencies",
            field=models.ManyToManyField(
                through="academic.StudentCompetency",
                to="curriculum.competency",
                verbose_name="Competências",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="student",
            name="estado",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("graduado", "Graduado"),
                    ("retido", "Retido"),
                    ("transferido", "Transferido"),
                ],
                default="active",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.competency",
                verbose_name="Competência",
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="nivel",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=3, verbose_name="Nível"
            ),
        ),
    ]
