# Generated by Django 5.1 on 2026-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('student_registered', 'Aluno registado'), ('assessment_recorded', 'Avaliação registada'), ('competency_updated', 'Competência atualizada'), ('cycle_completed', 'Ciclo concluído'), ('report_generated', 'Relatório gerado')], max_length=50, verbose_name='Tipo de evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do evento')),
                ('payload', models.JSONField(verbose_name='Dados')),
                ('tenant_id', models.CharField(max_length=50, verbose_name='Identificador do tenant')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
