# Generated by Django 5.2.12 on 2026-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={"verbose_name": "Event", "verbose_name_plural": "Eventos"},
        ),
        migrations.AlterField(
            model_name="evento",
            name="dados",
            field=models.JSONField(verbose_name="Dados"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tenant_id",
            field=models.CharField(max_length=50, verbose_name="ID do Tenant"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(max_length=50, verbose_name="Tipo"),
        ),
    ]
