# Generated by Django 5.1 on 2026-03-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_evento_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="dados",
            field=models.JSONField(verbose_name="Dados do Event"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data do Event"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("aluno_registrado", "Student Registrado"),
                    ("avaliacao_registrada", "Avaliação Registrada"),
                    ("competencia_atualizada", "Competência Atualizada"),
                    ("ciclo_concluido", "Ciclo Concluído"),
                    ("relatorio_gerado", "Relatório Gerado"),
                ],
                max_length=50,
                verbose_name="Tipo de Event",
            ),
        ),
    ]
