# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
                ('academic_year', models.CharField(max_length=10, verbose_name='Ano letivo')),
                ('decision_date', models.DateField(verbose_name='Data da decisão')),
                ('decision', models.CharField(choices=[('approved', 'Aprovado'), ('retained', 'Retido'), ('transferred', 'Transferido')], max_length=20, verbose_name='Decisão')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Progressão',
                'verbose_name_plural': 'Progressões',
                'ordering': ['-decision_date'],
            },
        ),
    ]
