# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("dados", models.JSONField()),
                ("tenant_id", models.CharField(max_length=50)),
            ],
        ),
    ]
