# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_evento_options_alter_evento_dados_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["-data"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
    ]
