# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("knowledge", models.BooleanField(default=False)),
                ("skills", models.BooleanField(default=False)),
                ("attitudes", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.competency",
                    ),
                ),
            ],
        ),
    ]
