# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("assessment", "0001_initial"),
        ("curriculum", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"verbose_name": "Avaliação", "verbose_name_plural": "Avaliações"},
        ),
        migrations.AlterField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="attitudes",
            field=models.BooleanField(default=False, verbose_name="Atitudes"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comentário"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="competency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.competency",
                verbose_name="Competência",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="knowledge",
            field=models.BooleanField(default=False, verbose_name="Conhecimentos"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="skills",
            field=models.BooleanField(default=False, verbose_name="Habilidades"),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Nota",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diagnostica", "Diagnóstica"),
                    ("formativa", "Formativa"),
                    ("sumativa", "Sumativa"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
