# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('assessment', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.competency', verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teachingassignment', verbose_name='Alocação docente'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='grade_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gradesubject', verbose_name='Disciplina da classe'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessmentcomponent', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='assessmentperiod',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='Ano letivo'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentperiod', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessmentperiod', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentperiod', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='teaching_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachingassignment', verbose_name='Alocação docente'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentperiod',
            unique_together={('academic_year', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together={('period', 'grade_subject', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectperiodresult',
            unique_together={('student', 'teaching_assignment', 'period')},
        ),
    ]
