# Generated by Django 5.1 on 2026-03-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentcomponent_tenant_id_and_more'),
        ('curriculum', '0004_competencyoutcome_learningoutcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentOutcomeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('weight', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Peso')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentcomponent', verbose_name='Componente')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.learningoutcome', verbose_name='Resultado de aprendizagem')),
            ],
            options={
                'verbose_name': 'Mapeamento componente-resultado',
                'verbose_name_plural': 'Mapeamentos componente-resultado',
                'ordering': ['component__name', 'outcome__code'],
                'unique_together': {('tenant_id', 'component', 'outcome')},
            },
        ),
    ]
