# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_aluno_options"),
        ("assessment", "0004_fase1_avaliacao_disciplinar"),
        ("school", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acs", "ACS"),
                            ("acp", "ACP"),
                            ("trabalho_individual", "Trabalho Individual"),
                            ("trabalho_grupo", "Trabalho em Grupo"),
                            ("teste", "Teste"),
                            ("exame", "Exame"),
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("outra", "Outra"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Nota Máxima",
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(default=True, verbose_name="Obrigatória"),
                ),
                (
                    "grade_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.disciplinaclasse",
                        verbose_name="Subject da Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente Avaliativa",
                "verbose_name_plural": "Componentes Avaliativas",
                "ordering": [
                    "periodo__ano_letivo__codigo",
                    "periodo__ordem",
                    "disciplina_classe__disciplina__nome",
                    "name",
                ],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.componenteavaliativa",
                verbose_name="Componente Avaliativa",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Ordem")),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                ("end_date", models.DateField(verbose_name="Data de Fim")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.anoletivo",
                        verbose_name="Ano Letivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Avaliativo",
                "verbose_name_plural": "Períodos Avaliativos",
                "ordering": ["ano_letivo__codigo", "order"],
                "unique_together": {("academic_year", "order")},
            },
        ),
        migrations.AddField(
            model_name="componenteavaliativa",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.periodoavaliativo",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.periodoavaliativo",
                verbose_name="Período",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="componenteavaliativa",
            unique_together={("period", "grade_subject", "name")},
        ),
        migrations.CreateModel(
            name="SubjectPeriodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Média Final",
                    ),
                ),
                (
                    "assessments_counted",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Avaliações Consideradas"
                    ),
                ),
                (
                    "teaching_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.alocacaodocente",
                        verbose_name="Alocação Docente",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                        verbose_name="Student",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.periodoavaliativo",
                        verbose_name="Período",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por Período e Subject",
                "verbose_name_plural": "Resultados por Período e Subject",
                "ordering": [
                    "periodo__ano_letivo__codigo",
                    "periodo__ordem",
                    "aluno__nome",
                ],
                "unique_together": {("student", "teaching_assignment", "period")},
            },
        ),
    ]
