# Generated by Django 5.1 on 2026-03-24 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentoutcomemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='assessmentoutcomemap',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='assessmentoutcomemap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='assessmentoutcomemap',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='assessmentoutcomemap',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='assessmentperiod',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='assessmentperiod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='assessmentperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='assessmentperiod',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='subjectperiodresult',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='assessmentperiod',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
