# Generated by Django 5.1 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_studentcompetency_unique_together_and_more'),
        ('assessment', '0005_assessment_code_assessment_created_at_and_more'),
        ('curriculum', '0005_basecurriculum_code_basecurriculum_created_at_and_more'),
        ('school', '0003_academicyear_created_at_academicyear_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentcomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentoutcomemap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentperiod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectperiodresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('period', 'grade_subject', 'name'), name='unique_assessment_component_active'),
        ),
        migrations.AddConstraint(
            model_name='assessmentoutcomemap',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'component', 'outcome'), name='unique_assessment_outcome_map_active'),
        ),
        migrations.AddConstraint(
            model_name='assessmentperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('academic_year', 'order'), name='unique_assessment_period_order_active'),
        ),
        migrations.AddConstraint(
            model_name='subjectperiodresult',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'teaching_assignment', 'period'), name='unique_subject_period_result_active'),
        ),
    ]
