# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurriculumArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("linguagem_comunicacao", "Linguagem e Comunicação"),
                            (
                                "saber_cientifico_tecnologico",
                                "Saber Científico e Tecnológico",
                            ),
                            (
                                "raciocinio_resolucao_problemas",
                                "Raciocínio e Resolução de Problemas",
                            ),
                            (
                                "desenvolvimento_pessoal_autonomia",
                                "Desenvolvimento Pessoal e Autonomia",
                            ),
                            (
                                "relacionamento_interpessoal",
                                "Relacionamento Interpessoal",
                            ),
                            ("bem_estar_saude_ambiente", "Bem-estar, Saúde e Ambiente"),
                            (
                                "sensibilidade_estetica_artistica",
                                "Sensibilidade Estética e Artística",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("cycle", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cycle", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.areacurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                ("cycle", models.IntegerField()),
                (
                    "additional_competencies",
                    models.ManyToManyField(blank=True, to="curriculum.competency"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle", models.IntegerField()),
                ("competencies", models.ManyToManyField(to="curriculum.competency")),
            ],
        ),
        migrations.AddField(
            model_name="competency",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.subject",
            ),
        ),
    ]
