# Generated by Django 5.1 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_studentcompetency_unique_together_and_more'),
        ('learning', '0002_assignment_code_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('assignment', 'student'), name='unique_submission_active'),
        ),
    ]
