"""
Django settings for schoolar_s project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q!^8qw3yxzb9mwr!%0)%92l_9cnlpclqn7z69rv+lt^dx=+$_b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SHARED_APPS = [
    # "django_tenants",  # mandatory
    # "tenants",  # you must list the app where your tenant model resides in

    # "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
]

TENANT_APPS = [
    # your tenant-specific apps
    "academico",
    "curriculo",
    "avaliacao",
    "progresso",
    "escola",
    "relatorios",
    "eventos",
]

INSTALLED_APPS = SHARED_APPS + TENANT_APPS  # list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# TENANT_MODEL = "tenants.Escola"  # app.Model

# TENANT_DOMAIN_MODEL = "tenants.Domain"  # app.Model

MIDDLEWARE = [
    # "django_tenants.middleware.main.TenantMainMiddleware",  # mandatory
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# DATABASE_ROUTERS = (
#     "django_tenants.routers.TenantSyncRouter",
# )

ROOT_URLCONF = "schoolar_s.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "schoolar_s.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-pt"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DRF settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # "DEFAULT_FILTER_BACKENDS": (
    #     "django_filters.rest_framework.DjangoFilterBackend",
    # ),
}

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Redis for cache (optional)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Jazzmin settings for modern admin theme
JAZZMIN_SETTINGS = {
    "site_title": "SUBSTRATO EDUCAÇÃO Admin",
    "site_header": "SUBSTRATO EDUCAÇÃO",
    "site_brand": "Schoolar-S",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Bem-vindo ao SUBSTRATO EDUCAÇÃO",
    "copyright": "SUBSTRATO EDUCAÇÃO Ltd",
    "search_model": ["academico.Aluno", "curriculo.Competencia"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "academico.Aluno"},
        {"app": "curriculo"},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["academico", "curriculo", "avaliacao", "progresso", "escola", "relatorios", "eventos"],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "academico.Aluno": "fas fa-user-graduate",
        "academico.AlunoCompetencia": "fas fa-chart-line",
        "curriculo.AreaCurricular": "fas fa-book",
        "curriculo.Disciplina": "fas fa-chalkboard-teacher",
        "curriculo.Competencia": "fas fa-target",
        "curriculo.CurriculoBase": "fas fa-file-alt",
        "curriculo.CurriculoLocal": "fas fa-map-marker-alt",
        "avaliacao.Avaliacao": "fas fa-clipboard-check",
        "progresso.Progressao": "fas fa-arrow-up",
        "escola.Professor": "fas fa-user-tie",
        "escola.Turma": "fas fa-users",
        "escola.Matricula": "fas fa-user-plus",
        "relatorios.Relatorio": "fas fa-chart-bar",
        "eventos.Evento": "fas fa-calendar-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

# Monkey patch for Django Context.__copy__ to fix Python 3.14 compatibility
from django.template.context import Context

def patched_copy(self):
    duplicate = Context(self.dicts)
    return duplicate

Context.__copy__ = patched_copy
