# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_fase1_estrutura_academica"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Distrito"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Província"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Escolas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManagementAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director_turma", "Director de Classroom"),
                            ("coordenador_classe", "Coordenador de Grade"),
                            ("director_ciclo", "Director de Ciclo"),
                            (
                                "director_adjunto_pedagogico",
                                "Director Adjunto Pedagógico",
                            ),
                            ("director_escola", "Director da School"),
                        ],
                        max_length=40,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "cycle",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ciclo"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.anoletivo",
                        verbose_name="Ano Letivo",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.grade",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.teacher",
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.classroom",
                        verbose_name="Classroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Gestão",
                "verbose_name_plural": "Atribuições de Gestão",
                "ordering": [
                    "ano_letivo__codigo",
                    "escola__nome",
                    "role",
                    "professor__nome",
                ],
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores",
                to="school.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas",
                to="school.school",
                verbose_name="School",
            ),
        ),
    ]
