# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areacurricular",
            options={
                "verbose_name": "Área Curricular",
                "verbose_name_plural": "Áreas Curriculares",
            },
        ),
        migrations.AlterModelOptions(
            name="competencia",
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculobase",
            options={
                "verbose_name": "Currículo Base",
                "verbose_name_plural": "Currículos Base",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculolocal",
            options={
                "verbose_name": "Currículo Local",
                "verbose_name_plural": "Currículos Locais",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.AlterField(
            model_name="areacurricular",
            name="nome",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="area",
            field=models.CharField(
                choices=[
                    ("linguagem_comunicacao", "Linguagem e Comunicação"),
                    ("saber_cientifico_tecnologico", "Saber Científico e Tecnológico"),
                    (
                        "raciocinio_resolucao_problemas",
                        "Raciocínio e Resolução de Problemas",
                    ),
                    (
                        "desenvolvimento_pessoal_autonomia",
                        "Desenvolvimento Pessoal e Autonomia",
                    ),
                    ("relacionamento_interpessoal", "Relacionamento Interpessoal"),
                    ("bem_estar_saude_ambiente", "Bem-estar, Saúde e Ambiente"),
                    (
                        "sensibilidade_estetica_artistica",
                        "Sensibilidade Estética e Artística",
                    ),
                ],
                max_length=50,
                verbose_name="Área",
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculo.disciplina",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="curriculobase",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="curriculobase",
            name="competencias",
            field=models.ManyToManyField(
                to="curriculo.competencia", verbose_name="Competências"
            ),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="competencias_adicionais",
            field=models.ManyToManyField(
                blank=True,
                to="curriculo.competencia",
                verbose_name="Competências Adicionais",
            ),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="tenant_id",
            field=models.CharField(max_length=50, verbose_name="ID do Tenant"),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculo.areacurricular",
                verbose_name="Área",
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
