# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculo", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencia",
            options={
                "ordering": ["nome"],
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculobase",
            options={
                "ordering": ["ciclo"],
                "verbose_name": "Currículo Base",
                "verbose_name_plural": "Currículos Base",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculolocal",
            options={
                "ordering": ["tenant_id", "ciclo"],
                "verbose_name": "Currículo Local",
                "verbose_name_plural": "Currículos Locais",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={
                "ordering": ["nome"],
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
    ]
