# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculo", "0003_alter_competencia_options_and_more"),
        ("escola", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoCurricularDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objetivos", models.TextField(blank=True, verbose_name="Objetivos")),
                (
                    "metodologia",
                    models.TextField(blank=True, verbose_name="Metodologia"),
                ),
                (
                    "criterios_avaliacao",
                    models.TextField(blank=True, verbose_name="Critérios de Avaliação"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "competencias_previstas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planos_curriculares",
                        to="curriculo.competencia",
                        verbose_name="Competências Previstas",
                    ),
                ),
                (
                    "disciplina_classe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plano_curricular",
                        to="escola.disciplinaclasse",
                        verbose_name="Disciplina da Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano Curricular por Disciplina",
                "verbose_name_plural": "Planos Curriculares por Disciplina",
                "ordering": [
                    "disciplina_classe__ano_letivo__codigo",
                    "disciplina_classe__classe__numero",
                ],
            },
        ),
    ]
