# Generated by Django 5.1 on 2026-03-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculo", "0004_planocurriculardisciplina"),
        ("escola", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competencia",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="escola.classe",
                verbose_name="Classe",
            ),
        ),
    ]
