# Generated by Django 5.1 on 2026-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Currículo base',
                'verbose_name_plural': 'Currículos base',
                'ordering': ['cycle'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('area', models.CharField(choices=[('language_communication', 'Linguagem e comunicação'), ('scientific_technological_knowledge', 'Saber científico e tecnológico'), ('reasoning_problem_solving', 'Raciocínio e resolução de problemas'), ('personal_development_autonomy', 'Desenvolvimento pessoal e autonomia'), ('interpersonal_relationship', 'Relacionamento interpessoal'), ('wellbeing_health_environment', 'Bem-estar, saúde e ambiente'), ('aesthetic_artistic_sensitivity', 'Sensibilidade estética e artística')], max_length=50, verbose_name='Área')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área curricular',
                'verbose_name_plural': 'Áreas curriculares',
            },
        ),
        migrations.CreateModel(
            name='LocalCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50, verbose_name='Identificador do tenant')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Currículo local',
                'verbose_name_plural': 'Currículos locais',
                'ordering': ['tenant_id', 'cycle'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True, verbose_name='Objetivos')),
                ('methodology', models.TextField(blank=True, verbose_name='Metodologia')),
                ('assessment_criteria', models.TextField(blank=True, verbose_name='Critérios de avaliação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano curricular por disciplina',
                'verbose_name_plural': 'Planos curriculares por disciplina',
                'ordering': ['grade_subject__academic_year__code', 'grade_subject__grade__number'],
            },
        ),
    ]
