# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areacurricular",
            options={
                "verbose_name": "Área Curricular",
                "verbose_name_plural": "Áreas Curriculares",
            },
        ),
        migrations.AlterModelOptions(
            name="competency",
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculobase",
            options={
                "verbose_name": "Currículo Base",
                "verbose_name_plural": "Currículos Base",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculolocal",
            options={
                "verbose_name": "Currículo Local",
                "verbose_name_plural": "Currículos Locais",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.AlterField(
            model_name="areacurricular",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="area",
            field=models.CharField(
                choices=[
                    ("linguagem_comunicacao", "Linguagem e Comunicação"),
                    ("saber_cientifico_tecnologico", "Saber Científico e Tecnológico"),
                    (
                        "raciocinio_resolucao_problemas",
                        "Raciocínio e Resolução de Problemas",
                    ),
                    (
                        "desenvolvimento_pessoal_autonomia",
                        "Desenvolvimento Pessoal e Autonomia",
                    ),
                    ("relacionamento_interpessoal", "Relacionamento Interpessoal"),
                    ("bem_estar_saude_ambiente", "Bem-estar, Saúde e Ambiente"),
                    (
                        "sensibilidade_estetica_artistica",
                        "Sensibilidade Estética e Artística",
                    ),
                ],
                max_length=50,
                verbose_name="Área",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="cycle",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="curriculobase",
            name="cycle",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="curriculobase",
            name="competencies",
            field=models.ManyToManyField(
                to="curriculum.competency", verbose_name="Competências"
            ),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="cycle",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="additional_competencies",
            field=models.ManyToManyField(
                blank=True,
                to="curriculum.competency",
                verbose_name="Competências Adicionais",
            ),
        ),
        migrations.AlterField(
            model_name="curriculolocal",
            name="tenant_id",
            field=models.CharField(max_length=50, verbose_name="ID do Tenant"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculum.areacurricular",
                verbose_name="Área",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="cycle",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
