# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.grade', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='basecurriculum',
            name='competencies',
            field=models.ManyToManyField(to='curriculum.competency', verbose_name='Competências'),
        ),
        migrations.AddField(
            model_name='localcurriculum',
            name='additional_competencies',
            field=models.ManyToManyField(blank=True, to='curriculum.competency', verbose_name='Competências adicionais'),
        ),
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumarea', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='competency',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='grade_subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plan', to='school.gradesubject', verbose_name='Disciplina da classe'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='planned_competencies',
            field=models.ManyToManyField(blank=True, related_name='curriculum_plans', to='curriculum.competency', verbose_name='Competências previstas'),
        ),
    ]
