# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competency",
            options={
                "ordering": ["name"],
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculobase",
            options={
                "ordering": ["cycle"],
                "verbose_name": "Currículo Base",
                "verbose_name_plural": "Currículos Base",
            },
        ),
        migrations.AlterModelOptions(
            name="curriculolocal",
            options={
                "ordering": ["tenant_id", "cycle"],
                "verbose_name": "Currículo Local",
                "verbose_name_plural": "Currículos Locais",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Disciplinas",
            },
        ),
    ]
