# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_alter_competencia_options_and_more"),
        ("school", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectCurriculumPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectives", models.TextField(blank=True, verbose_name="Objetivos")),
                (
                    "methodology",
                    models.TextField(blank=True, verbose_name="Metodologia"),
                ),
                (
                    "assessment_criteria",
                    models.TextField(blank=True, verbose_name="Critérios de Avaliação"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "planned_competencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planos_curriculares",
                        to="curriculum.competency",
                        verbose_name="Competências Previstas",
                    ),
                ),
                (
                    "grade_subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plano_curricular",
                        to="school.disciplinaclasse",
                        verbose_name="Subject da Grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano Curricular por Subject",
                "verbose_name_plural": "Planos Curriculares por Subject",
                "ordering": [
                    "disciplina_classe__ano_letivo__codigo",
                    "disciplina_classe__classe__numero",
                ],
            },
        ),
    ]
