# Generated by Django 5.1 on 2026-03-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_subjectcurriculumplan_tenant_id'),
        ('school', '0002_alter_gradesubject_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('weight', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Peso')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.competency', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Alinhamento competência-resultado',
                'verbose_name_plural': 'Alinhamentos competência-resultado',
                'ordering': ['outcome__code', 'competency__name'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cycle', models.IntegerField(verbose_name='Ciclo')),
                ('taxonomy_level', models.CharField(choices=[('remember', 'Recordar'), ('understand', 'Compreender'), ('apply', 'Aplicar'), ('analyze', 'Analisar'), ('evaluate', 'Avaliar'), ('create', 'Criar')], max_length=20, verbose_name='Nível cognitivo')),
                ('knowledge_dimension', models.CharField(blank=True, choices=[('factual', 'Factual'), ('conceptual', 'Conceitual'), ('procedural', 'Procedimental'), ('metacognitive', 'Metacognitivo')], max_length=20, verbose_name='Dimensão do conhecimento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('competencies', models.ManyToManyField(related_name='learning_outcomes', through='curriculum.CompetencyOutcome', to='curriculum.competency', verbose_name='Competências')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.grade', verbose_name='Classe')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Resultado de aprendizagem',
                'verbose_name_plural': 'Resultados de aprendizagem',
                'ordering': ['code'],
                'unique_together': {('tenant_id', 'code', 'subject', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='competencyoutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.learningoutcome', verbose_name='Resultado de aprendizagem'),
        ),
        migrations.AlterUniqueTogether(
            name='competencyoutcome',
            unique_together={('tenant_id', 'competency', 'outcome')},
        ),
    ]
