# Generated by Django 5.1 on 2026-03-24 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_competencyoutcome_learningoutcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecurriculum',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='basecurriculum',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='basecurriculum',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='basecurriculum',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='basecurriculum',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='competency',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='competency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='competency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='competency',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='competency',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='competencyoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='competencyoutcome',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='competencyoutcome',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='competencyoutcome',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='curriculumarea',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='localcurriculum',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='localcurriculum',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='localcurriculum',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='localcurriculum',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='subjectcurriculumplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='curriculumarea',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='localcurriculum',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='curriculumarea',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_curriculumarea_name'),
        ),
    ]
