# Generated by Django 5.1 on 2026-03-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_planocurriculardisciplina"),
        ("school", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competency",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="school.grade",
                verbose_name="Grade",
            ),
        ),
    ]
