# Generated by Django 5.1 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_basecurriculum_code_basecurriculum_created_at_and_more'),
        ('school', '0003_academicyear_created_at_academicyear_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curriculumarea',
            name='unique_curriculumarea_name',
        ),
        migrations.AlterUniqueTogether(
            name='competencyoutcome',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='learningoutcome',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='competencyoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'competency', 'outcome'), name='unique_competency_outcome_active'),
        ),
        migrations.AddConstraint(
            model_name='curriculumarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_curriculumarea_name'),
        ),
        migrations.AddConstraint(
            model_name='learningoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'code', 'subject', 'grade'), name='unique_learning_outcome_active'),
        ),
    ]
