# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academico",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("escola", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={"verbose_name": "Matrícula", "verbose_name_plural": "Matrículas"},
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "Professor", "verbose_name_plural": "Professores"},
        ),
        migrations.AlterModelOptions(
            name="turma",
            options={"verbose_name": "Turma", "verbose_name_plural": "Turmas"},
        ),
        migrations.AlterField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academico.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="data_matricula",
            field=models.DateField(auto_now_add=True, verbose_name="Data da Matrícula"),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="escola.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="especialidade",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Especialidade"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="ano_letivo",
            field=models.CharField(max_length=10, verbose_name="Ano Letivo"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="nome",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="professor_responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="escola.professor",
                verbose_name="Professor Responsável",
            ),
        ),
    ]
