# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_alter_matricula_options_alter_professor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={
                "ordering": ["-data_matricula"],
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.AlterModelOptions(
            name="professor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AlterModelOptions(
            name="turma",
            options={
                "ordering": ["nome"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
    ]
