# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academico",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorio",
            options={"verbose_name": "Relatório", "verbose_name_plural": "Relatórios"},
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="aluno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academico.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="conteudo",
            field=models.JSONField(verbose_name="Conteúdo"),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="data_geracao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Geração"
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="periodo",
            field=models.CharField(blank=True, max_length=50, verbose_name="Período"),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("aluno", "Relatório de Aluno"),
                    ("escola", "Relatório de Escola"),
                    ("nacional", "Relatório Nacional"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
    ]
