# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("curriculo", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"verbose_name": "Aluno", "verbose_name_plural": "Alunos"},
        ),
        migrations.AlterModelOptions(
            name="alunocompetencia",
            options={
                "verbose_name": "Competência do Aluno",
                "verbose_name_plural": "Competências dos Alunos",
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ciclo",
            field=models.IntegerField(
                choices=[(1, "1º Ciclo"), (2, "2º Ciclo")], verbose_name="Ciclo"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="classe",
            field=models.IntegerField(verbose_name="Classe"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="competencias",
            field=models.ManyToManyField(
                through="academico.AlunoCompetencia",
                to="curriculo.competencia",
                verbose_name="Competências",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("graduado", "Graduado"),
                    ("retido", "Retido"),
                    ("transferido", "Transferido"),
                ],
                default="ativo",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academico.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="competencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculo.competencia",
                verbose_name="Competência",
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="alunocompetencia",
            name="nivel",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=3, verbose_name="Nível"
            ),
        ),
    ]
