# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "academico",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={
                "ordering": ["nome"],
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
    ]
