# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle", models.IntegerField()),
                ("academic_year", models.CharField(max_length=10)),
                ("data_decisao", models.DateField()),
                (
                    "decisao",
                    models.CharField(
                        choices=[
                            ("aprovado", "Aprovado"),
                            ("retido", "Retido"),
                            ("transferido", "Transferido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                    ),
                ),
            ],
        ),
    ]
