# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_alter_progressao_options_alter_progressao_aluno_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progressao",
            options={
                "ordering": ["-data_decisao"],
                "verbose_name": "Progressão",
                "verbose_name_plural": "Progressões",
            },
        ),
    ]
