# Generated by Django 5.1 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_subjectcurriculumplan_tenant_id'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradesubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='school',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Identificador do tenant'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='code',
            field=models.CharField(max_length=9, verbose_name='Ano letivo'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('tenant_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('tenant_id', 'name', 'grade', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='gradesubject',
            unique_together={('tenant_id', 'academic_year', 'grade', 'subject')},
        ),
    ]
