# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name": "Matrícula", "verbose_name_plural": "Matrículas"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Professores"},
        ),
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "Classroom", "verbose_name_plural": "Turmas"},
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Data da Matrícula"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.classroom",
                verbose_name="Classroom",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Especialidade"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="academic_year",
            field=models.CharField(max_length=10, verbose_name="Ano Letivo"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="cycle",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="lead_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.teacher",
                verbose_name="Teacher Responsável",
            ),
        ),
    ]
