# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_matricula_options_alter_professor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-enrollment_date"],
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["name"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": ["name"],
                "verbose_name": "Classroom",
                "verbose_name_plural": "Turmas",
            },
        ),
    ]
