# Generated by Django 5.1 on 2026-03-24 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_gradesubject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='grade',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='grade',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='managementassignment',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='managementassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='managementassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='managementassignment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='school',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='auditalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
