# Generated by Django 5.1 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_studentcompetency_unique_together_and_more'),
        ('curriculum', '0006_remove_curriculumarea_unique_curriculumarea_name_and_more'),
        ('school', '0003_academicyear_created_at_academicyear_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gradesubject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'code'), name='unique_academic_year_code_active'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'name', 'grade', 'academic_year'), name='unique_classroom_active'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'classroom'), name='unique_enrollment_active'),
        ),
        migrations.AddConstraint(
            model_name='gradesubject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'academic_year', 'grade', 'subject'), name='unique_grade_subject_active'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('classroom', 'grade_subject'), name='unique_teaching_assignment_active'),
        ),
    ]
