# Generated by Django 5.2.12 on 2026-03-28 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0008_subjectspecialty"),
        ("school", "0005_academicyear_usuario_announcement_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="specialty_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculum.subjectspecialty",
                verbose_name="Especialidade (referência)",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="specialty",
            field=models.CharField(
                blank=True, editable=False, max_length=100, verbose_name="Especialidade"
            ),
        ),
    ]
