# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nível')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Competência do aluno',
                'verbose_name_plural': 'Competências dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact', models.BooleanField(default=False, verbose_name='Contato principal')),
                ('receives_notifications', models.BooleanField(default=True, verbose_name='Recebe notificações')),
            ],
            options={
                'verbose_name': 'Relação aluno-encarregado',
                'verbose_name_plural': 'Relações aluno-encarregado',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('relationship', models.CharField(blank=True, max_length=60, verbose_name='Parentesco')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Encarregado',
                'verbose_name_plural': 'Encarregados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('grade', models.IntegerField(verbose_name='Classe')),
                ('cycle', models.IntegerField(choices=[(1, '1º Ciclo'), (2, '2º Ciclo')], verbose_name='Ciclo')),
                ('estado', models.CharField(choices=[('active', 'Ativo'), ('graduado', 'Graduado'), ('retido', 'Retido'), ('transferido', 'Transferido')], default='active', max_length=20, verbose_name='Estado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['name'],
            },
        ),
    ]
