# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.competency', verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='studentcompetency',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='student',
            name='competencies',
            field=models.ManyToManyField(through='academic.StudentCompetency', to='curriculum.competency', verbose_name='Competências'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.guardian', verbose_name='Encarregado'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcompetency',
            unique_together={('student', 'competency')},
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together={('student', 'guardian')},
        ),
    ]
