# Generated by Django 5.1 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentcompetency',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together={('tenant_id', 'student', 'guardian')},
        ),
    ]
