# Generated by Django 5.1 on 2026-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_studentguardian_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant')),
                ('mastery_level', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nível')),
                ('status', models.CharField(choices=[('not_started', 'Não iniciado'), ('developing', 'Em desenvolvimento'), ('proficient', 'Proficiente'), ('advanced', 'Avançado')], default='not_started', max_length=20, verbose_name='Estado')),
                ('evidence_count', models.PositiveIntegerField(default=0, verbose_name='Evidências')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Resultado do aluno',
                'verbose_name_plural': 'Resultados do aluno',
                'ordering': ['-updated_at'],
            },
        ),
    ]
