# Generated by Django 5.1 on 2026-03-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_studentoutcome'),
        ('curriculum', '0004_competencyoutcome_learningoutcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.learningoutcome', verbose_name='Resultado de aprendizagem'),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='studentoutcome',
            unique_together={('tenant_id', 'student', 'outcome')},
        ),
    ]
