# Generated by Django 5.1 on 2026-03-24 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_studentoutcome_outcome_studentoutcome_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='studentcompetency',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='studentcompetency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='studentcompetency',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='studentoutcome',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removido em'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='studentcompetency',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
    ]
