# Generated by Django 5.1 on 2026-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_guardian_code_guardian_created_at_and_more'),
        ('curriculum', '0005_basecurriculum_code_basecurriculum_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcompetency',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentoutcome',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentcompetency',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('student', 'competency'), name='unique_student_competency_active'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'student', 'guardian'), name='unique_student_guardian_active'),
        ),
        migrations.AddConstraint(
            model_name='studentoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant_id', 'student', 'outcome'), name='unique_student_outcome_active'),
        ),
    ]
