# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academico",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("avaliacao", "0001_initial"),
        ("curriculo", "0002_alter_areacurricular_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={"verbose_name": "Avaliação", "verbose_name_plural": "Avaliações"},
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academico.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="atitudes",
            field=models.BooleanField(default=False, verbose_name="Atitudes"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="comentario",
            field=models.TextField(blank=True, verbose_name="Comentário"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="competencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculo.competencia",
                verbose_name="Competência",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="conhecimentos",
            field=models.BooleanField(default=False, verbose_name="Conhecimentos"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="habilidades",
            field=models.BooleanField(default=False, verbose_name="Habilidades"),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Nota",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("diagnostica", "Diagnóstica"),
                    ("formativa", "Formativa"),
                    ("sumativa", "Sumativa"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
