# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao", "0002_alter_avaliacao_options_alter_avaliacao_aluno_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={
                "ordering": ["-data"],
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
            },
        ),
    ]
