# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0004_fase1_estrutura_academica"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "distrito",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Distrito"
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Província"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoGestao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("director_turma", "Director de Turma"),
                            ("coordenador_classe", "Coordenador de Classe"),
                            ("director_ciclo", "Director de Ciclo"),
                            (
                                "director_adjunto_pedagogico",
                                "Director Adjunto Pedagógico",
                            ),
                            ("director_escola", "Director da Escola"),
                        ],
                        max_length=40,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "ciclo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ciclo"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.anoletivo",
                        verbose_name="Ano Letivo",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.classe",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.professor",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.turma",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.escola",
                        verbose_name="Escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Gestão",
                "verbose_name_plural": "Atribuições de Gestão",
                "ordering": [
                    "ano_letivo__codigo",
                    "escola__nome",
                    "cargo",
                    "professor__nome",
                ],
            },
        ),
        migrations.AddField(
            model_name="professor",
            name="escola",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores",
                to="escola.escola",
                verbose_name="Escola",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="escola",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas",
                to="escola.escola",
                verbose_name="Escola",
            ),
        ),
    ]
