# Generated by Django 5.2.12 on 2026-03-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academico",
            "0002_alter_aluno_options_alter_alunocompetencia_options_and_more",
        ),
        ("progresso", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progressao",
            options={
                "verbose_name": "Progressão",
                "verbose_name_plural": "Progressões",
            },
        ),
        migrations.AlterField(
            model_name="progressao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academico.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="progressao",
            name="ano_letivo",
            field=models.CharField(max_length=10, verbose_name="Ano Letivo"),
        ),
        migrations.AlterField(
            model_name="progressao",
            name="ciclo",
            field=models.IntegerField(verbose_name="Ciclo"),
        ),
        migrations.AlterField(
            model_name="progressao",
            name="comentario",
            field=models.TextField(blank=True, verbose_name="Comentário"),
        ),
        migrations.AlterField(
            model_name="progressao",
            name="data_decisao",
            field=models.DateField(verbose_name="Data da Decisão"),
        ),
        migrations.AlterField(
            model_name="progressao",
            name="decisao",
            field=models.CharField(
                choices=[
                    ("aprovado", "Aprovado"),
                    ("retido", "Retido"),
                    ("transferido", "Transferido"),
                ],
                max_length=20,
                verbose_name="Decisão",
            ),
        ),
    ]
