# Generated by Django 5.1 on 2026-03-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0003_alter_aluno_options"),
        ("avaliacao", "0004_fase1_avaliacao_disciplinar"),
        ("escola", "0005_escola_atribuicaogestao_professor_escola_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteAvaliativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acs", "ACS"),
                            ("acp", "ACP"),
                            ("trabalho_individual", "Trabalho Individual"),
                            ("trabalho_grupo", "Trabalho em Grupo"),
                            ("teste", "Teste"),
                            ("exame", "Exame"),
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("outra", "Outra"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                (
                    "nota_maxima",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Nota Máxima",
                    ),
                ),
                (
                    "obrigatoria",
                    models.BooleanField(default=True, verbose_name="Obrigatória"),
                ),
                (
                    "disciplina_classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.disciplinaclasse",
                        verbose_name="Disciplina da Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente Avaliativa",
                "verbose_name_plural": "Componentes Avaliativas",
                "ordering": [
                    "periodo__ano_letivo__codigo",
                    "periodo__ordem",
                    "disciplina_classe__disciplina__nome",
                    "nome",
                ],
            },
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="componente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="avaliacao.componenteavaliativa",
                verbose_name="Componente Avaliativa",
            ),
        ),
        migrations.CreateModel(
            name="PeriodoAvaliativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("ordem", models.PositiveSmallIntegerField(verbose_name="Ordem")),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.anoletivo",
                        verbose_name="Ano Letivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Avaliativo",
                "verbose_name_plural": "Períodos Avaliativos",
                "ordering": ["ano_letivo__codigo", "ordem"],
                "unique_together": {("ano_letivo", "ordem")},
            },
        ),
        migrations.AddField(
            model_name="componenteavaliativa",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="avaliacao.periodoavaliativo",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="avaliacao.periodoavaliativo",
                verbose_name="Período",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="componenteavaliativa",
            unique_together={("periodo", "disciplina_classe", "nome")},
        ),
        migrations.CreateModel(
            name="ResultadoPeriodoDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Média Final",
                    ),
                ),
                (
                    "avaliacoes_consideradas",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Avaliações Consideradas"
                    ),
                ),
                (
                    "alocacao_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.alocacaodocente",
                        verbose_name="Alocação Docente",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="avaliacao.periodoavaliativo",
                        verbose_name="Período",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por Período e Disciplina",
                "verbose_name_plural": "Resultados por Período e Disciplina",
                "ordering": [
                    "periodo__ano_letivo__codigo",
                    "periodo__ordem",
                    "aluno__nome",
                ],
                "unique_together": {("aluno", "alocacao_docente", "periodo")},
            },
        ),
    ]
