# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("student", "Relatório de Student"),
                            ("school", "Relatório de School"),
                            ("nacional", "Relatório Nacional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                ("period", models.CharField(blank=True, max_length=50)),
                ("conteudo", models.JSONField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.student",
                    ),
                ),
            ],
        ),
    ]
