# Generated by Django 5.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('type', models.CharField(choices=[('student', 'Relatório do aluno'), ('school', 'Relatório da escola'), ('national', 'Relatório nacional')], max_length=20, verbose_name='Tipo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de geração')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='Período')),
                ('content', models.JSONField(verbose_name='Conteúdo')),
                ('serial_number', models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='Número de série')),
                ('verification_code', models.CharField(blank=True, editable=False, max_length=32, unique=True, verbose_name='Código de verificação')),
                ('verification_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Assinatura de verificação')),
                ('verification_version', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Versão de verificação')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-generated_at'],
            },
        ),
    ]
