# Generated by Django 5.1 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificador do tenant'),
        ),
    ]
