# Generated by Django 5.1 on 2026-03-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_relatorio_options_alter_relatorio_aluno_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorio",
            options={
                "ordering": ["-data_geracao"],
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
            },
        ),
    ]
