# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("classe", models.IntegerField()),
                (
                    "ciclo",
                    models.IntegerField(choices=[(1, "1º Ciclo"), (2, "2º Ciclo")]),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("graduado", "Graduado"),
                            ("retido", "Retido"),
                            ("transferido", "Transferido"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlunoCompetencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.aluno",
                    ),
                ),
                (
                    "competencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculo.competencia",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "competencia")},
            },
        ),
        migrations.AddField(
            model_name="aluno",
            name="competencias",
            field=models.ManyToManyField(
                through="academico.AlunoCompetencia", to="curriculo.competencia"
            ),
        ),
    ]
