# Generated by Django 4.2 on 2026-03-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("linguagem_comunicacao", "Linguagem e Comunicação"),
                            (
                                "saber_cientifico_tecnologico",
                                "Saber Científico e Tecnológico",
                            ),
                            (
                                "raciocinio_resolucao_problemas",
                                "Raciocínio e Resolução de Problemas",
                            ),
                            (
                                "desenvolvimento_pessoal_autonomia",
                                "Desenvolvimento Pessoal e Autonomia",
                            ),
                            (
                                "relacionamento_interpessoal",
                                "Relacionamento Interpessoal",
                            ),
                            ("bem_estar_saude_ambiente", "Bem-estar, Saúde e Ambiente"),
                            (
                                "sensibilidade_estetica_artistica",
                                "Sensibilidade Estética e Artística",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("ciclo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ciclo", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculo.areacurricular",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurriculoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=50)),
                ("ciclo", models.IntegerField()),
                (
                    "competencias_adicionais",
                    models.ManyToManyField(blank=True, to="curriculo.competencia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurriculoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciclo", models.IntegerField()),
                ("competencias", models.ManyToManyField(to="curriculo.competencia")),
            ],
        ),
        migrations.AddField(
            model_name="competencia",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="curriculo.disciplina",
            ),
        ),
    ]
